import { createContext, useContext, useMemo, useState, type ReactNode } from 'react'
import type { CalendarContextRow, CalendarRow, ExpectedSalesRow, ForecastRow, InventoryForecastRow } from '../types/api'

export type InventoryForecastDraft={source:'Forecasting';createdAt:string;forecasts:InventoryForecastRow[]}
export type AnomalyExpectedDraft={source:'Forecasting';createdAt:string;expectedSales:ExpectedSalesRow[];calendarContext:CalendarContextRow[]}
type DraftContextValue={inventoryDraft:InventoryForecastDraft|null;anomalyDraft:AnomalyExpectedDraft|null;createInventoryDraft:(rows:ForecastRow[])=>void;createAnomalyDraft:(rows:ForecastRow[],calendar:CalendarRow[])=>void;clearInventoryDraft:()=>void;clearAnomalyDraft:()=>void}
const DraftContext=createContext<DraftContextValue|null>(null)
export function ForecastDraftProvider({children}:{children:ReactNode}){const[inventoryDraft,setInventoryDraft]=useState<InventoryForecastDraft|null>(null),[anomalyDraft,setAnomalyDraft]=useState<AnomalyExpectedDraft|null>(null);const value=useMemo<DraftContextValue>(()=>({inventoryDraft,anomalyDraft,createInventoryDraft:(rows)=>setInventoryDraft({source:'Forecasting',createdAt:new Date().toISOString(),forecasts:rows.map(r=>({forecast_date:r.date,store_id:r.store_id,dept_id:r.dept_id,predicted_sales:r.predicted_sales}))}),createAnomalyDraft:(rows,calendar)=>{const byDate=new Map(calendar.map(r=>[r.date.slice(0,10),r]));setAnomalyDraft({source:'Forecasting',createdAt:new Date().toISOString(),expectedSales:rows.map(r=>({date:r.date,store_id:r.store_id,dept_id:r.dept_id,expected_sales:r.predicted_sales})),calendarContext:rows.flatMap(r=>{const c=byDate.get(r.date.slice(0,10));return c?[{date:r.date,event_name:c.event_name,event_type:c.event_type,snap_CA:c.snap_CA,snap_TX:c.snap_TX,snap_WI:c.snap_WI}]:[]})})},clearInventoryDraft:()=>setInventoryDraft(null),clearAnomalyDraft:()=>setAnomalyDraft(null)}),[inventoryDraft,anomalyDraft]);return <DraftContext.Provider value={value}>{children}</DraftContext.Provider>}
export function useForecastDrafts(){const value=useContext(DraftContext);if(!value)throw new Error('useForecastDrafts must be used within ForecastDraftProvider');return value}
