import type { ReactNode } from 'react'
import { AlertTriangle, CircleAlert, Database, LoaderCircle, Play, RefreshCw } from 'lucide-react'
import { ApiError } from '../api/client'

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: ReactNode }) { return <header className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{actions && <div className="actions">{actions}</div>}</header> }
export function SectionCard({ title, description, children, className = '' }: { title?: string; description?: string; children: ReactNode; className?: string }) { return <section className={`card ${className}`}>{title && <div className="card-header"><div><h2>{title}</h2>{description && <p className="muted small">{description}</p>}</div></div>}{children}</section> }
export function StatusBadge({ status, children }: { status: 'success'|'warning'|'danger'|'info'; children: ReactNode }) { return <span className={`badge ${status}`}>{children}</span> }
export function Banner({ tone = 'info', title, children }: { tone?: 'info'|'warning'|'danger'|'success'; title: string; children: ReactNode }) { const Icon = tone === 'danger' ? CircleAlert : AlertTriangle; return <div className={`banner ${tone}`} role={tone === 'danger' ? 'alert' : 'status'}><Icon size={18} aria-hidden="true"/><div className="banner-content"><strong>{title}</strong><div>{children}</div></div></div> }
export function Warnings({ warnings }: { warnings?: string[] }) { if (!warnings?.length) return null; return <div aria-label="Model warnings">{warnings.map((w,i)=><Banner tone="warning" title="Important interpretation" key={`${w}-${i}`}>{w}</Banner>)}</div> }
export function ErrorState({ error }: { error: unknown }) { const e = error instanceof ApiError ? error : new ApiError(null,'CLIENT_ERROR','Something went wrong.'); return <div aria-live="assertive"><Banner tone="danger" title={e.code}>{e.message}{Array.isArray(e.details) && <ul>{e.details.map((d:any,i)=><li key={i}>{d.field}: {d.message}</li>)}</ul>}{e.requestId && <div className="diagnostic">Request ID: {e.requestId}</div>}</Banner></div> }
export function LoadingState({ label='Loading' }: { label?:string }) { return <div className="card" role="status" aria-live="polite"><span className="sr-only">{label}</span><div className="skeleton"/><div className="skeleton"/><div className="skeleton"/></div> }
export function EmptyState({ title='Ready when you are', children }: { title?:string; children:ReactNode }) { return <div className="empty"><div><Database size={28} aria-hidden="true"/><h2>{title}</h2><p>{children}</p></div></div> }
export function MetricCard({ label, value, detail }: { label:string; value:ReactNode; detail?:ReactNode }) { return <div className="card metric"><div className="metric-label">{label}</div><div className="metric-value">{value}</div>{detail && <div className="metric-detail">{detail}</div>}</div> }
export function RunButton({ pending, children='Run analysis' }: { pending:boolean; children?:ReactNode }) { return <button className="button" type="submit" disabled={pending}>{pending?<><LoaderCircle size={17} aria-hidden="true"/>Running…</>:<><Play size={17} aria-hidden="true"/>{children}</>}</button> }
export function RefreshButton({ pending, onClick }: { pending:boolean; onClick:()=>void }) { return <button type="button" className="button secondary" onClick={onClick} disabled={pending}><RefreshCw size={16} aria-hidden="true"/>Refresh</button> }
export function Table({ caption, headers, rows }: { caption:string; headers:string[]; rows:ReactNode[][] }) { return <div className="table-region" tabIndex={0} role="region" aria-label={`${caption}, scroll horizontally for all columns`}><table className="table"><caption>{caption}</caption><thead><tr>{headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div> }
export function ChartContainer({ title, summary, children }: { title:string; summary:string; children:ReactNode }) { return <figure aria-labelledby={`${title.replace(/\W/g,'-')}-title`}><h2 id={`${title.replace(/\W/g,'-')}-title`}>{title}</h2><div className="chart" aria-hidden="true">{children}</div><figcaption className="chart-summary">{summary}</figcaption></figure> }
