import type { AnomalyRequest, ForecastRequest, InventoryRequest, RecommendationRequest, ReturnRiskRequest, SegmentationRequest } from '../types/api'
const iso=(date:Date)=>date.toISOString().slice(0,10)
export const demoLabels={forecast:'Illustrative M5-shaped input — synthetic sales values; no stored model output',segments:'Illustrative prepared Complete Journey-shaped features — synthetic input',risk:'Illustrative Complete Journey-shaped transactions — synthetic input',recommendations:'Illustrative RetailRocket-shaped compact history — synthetic IDs; may use fallback',anomalies:'Illustrative M5-shaped preview rows — synthetic actual/expected inputs',inventory:'SYNTHETIC BUSINESS INVENTORY STATE — M5 has no inventory balances'}
export function forecastDemo():ForecastRequest{const start=new Date('2016-03-28T00:00:00Z');const history=Array.from({length:56},(_,i)=>{const d=new Date(start);d.setUTCDate(d.getUTCDate()+i);return{d:`d_${1886+i}`,date:iso(d),store_id:'CA_1',dept_id:'FOODS_1',state_id:'CA',sales:90+(i%7)*3}});const future_calendar=Array.from({length:28},(_,i)=>{const d=new Date(start);d.setUTCDate(d.getUTCDate()+56+i);return{d:`d_${1942+i}`,date:iso(d),event_name:'none',event_type:'none',snap_CA:0,snap_TX:0,snap_WI:0}});return{history,future_calendar}}
export const segmentDemo:SegmentationRequest={snapshot_at:'2017-09-30T23:59:59Z',feature_rows:[{household_id:101,recency_days:10,basket_frequency:12,monetary_value:540,avg_basket_value:45,unique_departments:6,department_spend_hhi:.24,discount_share_of_gross:.11,coupon_basket_rate:.08,private_label_spend_share:.2},{household_id:102,recency_days:45,basket_frequency:5,monetary_value:180,avg_basket_value:36,unique_departments:3,department_spend_hhi:.48,discount_share_of_gross:.05,coupon_basket_rate:0,private_label_spend_share:.1}]}
export const riskDemo:ReturnRiskRequest={snapshot_at:'2017-11-30T23:59:59Z',capacity:.1,transactions:['2017-08-01','2017-08-25','2017-09-20','2017-10-15','2017-11-10'].map((date,i)=>({household_id:101,store_id:1,basket_id:i+1,product_id:1,sales_value:10,retail_disc:0,coupon_disc:0,coupon_match_disc:0,transaction_timestamp:`${date}T12:00:00Z`})),products:[{product_id:1,department:'GROCERY',brand:'NATIONAL'}]}
export const recommendationDemo:RecommendationRequest={visitor_id:42,snapshot_timestamp:'2015-09-18T03:00:00Z',k:10,history_item_ids:[1001,1002]}
export const anomalyDemo:AnomalyRequest={actual_sales:[{date:'2016-05-23',store_id:'CA_1',dept_id:'FOODS_1',actual_sales:120},{date:'2016-05-24',store_id:'CA_1',dept_id:'FOODS_1',actual_sales:70}],expected_sales:[{date:'2016-05-23',store_id:'CA_1',dept_id:'FOODS_1',expected_sales:100},{date:'2016-05-24',store_id:'CA_1',dept_id:'FOODS_1',expected_sales:100}],include_if_diagnostic:false}
export function inventoryDemo():InventoryRequest{return{inventory_inputs:[{snapshot_date:'2016-05-22',store_id:'CA_1',dept_id:'FOODS_1',on_hand_inventory:100,on_order_inventory:0,backorders:0,lead_time_days:7,review_period_days:7,service_level_target:.95,uncertainty_method:'robust_normal'}],forecasts:Array.from({length:28},(_,i)=>{const d=new Date('2016-05-23T00:00:00Z');d.setUTCDate(d.getUTCDate()+i);return{forecast_date:iso(d),store_id:'CA_1',dept_id:'FOODS_1',predicted_sales:10}})}}
