import { useEffect, useRef, useState } from 'react'
import { Activity, Boxes, ChartNoAxesCombined, House, Menu, PackageSearch, ShieldAlert, ShoppingBag, Sparkles, TrendingUp, Users, X } from 'lucide-react'
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom'
import { useReady } from '../api/queries'

const groups=[{label:'',links:[['/','Overview',House]]},{label:'Intelligence',links:[['/forecasting','Forecasting',ChartNoAxesCombined],['/recommendations','Recommendations',Sparkles],['/anomalies','Anomalies',ShieldAlert],['/inventory','Inventory',Boxes]]},{label:'Customers',links:[['/customers/segments','Segmentation',Users],['/customers/return-risk','Re-engagement',Activity]]},{label:'System',links:[['/system/models','Models',PackageSearch]]}] as const
const focusable='a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])'

function ProductMark({compact=false}:{compact?:boolean}){return <div className={`product-mark ${compact?'compact':''}`}><span className="brand-mark"><ShoppingBag size={18} aria-hidden="true"/><TrendingUp className="brand-trend" size={12} aria-hidden="true"/></span><span className="brand-copy"><strong>MarketMind AI</strong>{!compact&&<small>Retail intelligence workspace.</small>}</span></div>}

function ReadinessIndicator({compact=false}:{compact?:boolean}){const ready=useReady(),modules=ready.data?Object.values(ready.data.modules).filter(Boolean).length:0;const tone=ready.isError?'danger':ready.data?.status==='ready'?'positive':ready.data?.status==='degraded'?'warning':'checking';const label=ready.isError?'API unavailable':ready.data?.status==='ready'?`${modules} engines ready`:ready.data?.status==='degraded'?`${modules} of 6 engines ready`:'Checking systems…';return <Link className={`readiness ${tone} ${compact?'compact':''}`} to="/system/models" aria-label={`${label}. View Models and API.`}><span className="readiness-dot" aria-hidden="true"/><span>{compact&&ready.data?`${modules}/6`:label}</span></Link>}

export function AppShell(){const [open,setOpen]=useState(false);const openRef=useRef<HTMLButtonElement>(null),closeRef=useRef<HTMLButtonElement>(null),drawerRef=useRef<HTMLElement>(null);const location=useLocation();useEffect(()=>{setOpen(false);document.getElementById('main-content')?.focus()},[location.pathname]);useEffect(()=>{if(!open)return;setTimeout(()=>closeRef.current?.focus(),0);const keyboard=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setOpen(false);openRef.current?.focus();return}if(e.key!=='Tab')return;const items=Array.from(drawerRef.current?.querySelectorAll<HTMLElement>(focusable)??[]);if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}};document.addEventListener('keydown',keyboard);return()=>document.removeEventListener('keydown',keyboard)},[open]);const close=()=>{setOpen(false);openRef.current?.focus()};return <div className="app"><a className="skip-link" href="#main-content">Skip to content</a><header className="mobile-header"><ProductMark compact/><div className="mobile-tools"><ReadinessIndicator compact/><button ref={openRef} className="menu-button" aria-label="Open navigation" aria-expanded={open} aria-controls="primary-navigation" onClick={()=>setOpen(true)}><Menu aria-hidden="true"/></button></div></header><button className={`drawer-backdrop ${open?'open':''}`} aria-label="Close navigation" onClick={close}/><aside ref={drawerRef} id="primary-navigation" className={`sidebar ${open?'open':''}`} aria-label="Primary navigation"><div className="sidebar-head"><ProductMark/>{open&&<button ref={closeRef} className="menu-button" aria-label="Close navigation" onClick={close}><X aria-hidden="true"/></button>}</div><nav>{groups.map(g=><div className="nav-group" key={g.label||'overview'}>{g.label&&<div className="nav-label">{g.label}</div>}{g.links.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} title={label} className={({isActive})=>`nav-link ${isActive?'active':''}`}><Icon size={18} aria-hidden="true"/><span>{label}</span></NavLink>)}</div>)}</nav><div className="sidebar-foot"><ReadinessIndicator/></div></aside><main className="main"><div id="main-content" className="content" tabIndex={-1}><Outlet/></div></main></div>}
