import { useMemo, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, CalendarDays, ScanSearch } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../../api/client'
import { useInference } from '../../api/queries'
import { Banner, ChartContainer, Disclosure, EmptyState, ErrorState, PageHeader, RunButton, StatusBadge, Table, Warnings } from '../../components/ui'
import { JsonEditor } from '../../components/JsonEditor'
import { anomalyDemo, demoLabels } from '../../demo/fixtures'
import type { ActualSalesRow, AnomalyRequest, CalendarContextRow, ExpectedSalesRow } from '../../types/api'
import { useForecastDrafts } from '../../app/ForecastDraftContext'

export function AnomaliesPage() {
  const drafts = useForecastDrafts(), imported = drafts.anomalyDraft
  const [actual, setActual] = useState<ActualSalesRow[]>(() => imported ? [] : anomalyDemo.actual_sales)
  const [expected, setExpected] = useState<ExpectedSalesRow[]>(() => imported ? imported.expectedSales : anomalyDemo.expected_sales)
  const [calendar, setCalendar] = useState<CalendarContextRow[]>(() => imported ? imported.calendarContext : [])
  const [includeIf, setIncludeIf] = useState(false)
  const mutation = useInference<AnomalyRequest, Awaited<ReturnType<typeof api.anomalies>>>(api.anomalies)
  const rows = mutation.data?.rows ?? [], priority = rows.filter(row => row.is_review_priority)
  const actualFirst = actual[0]
  const expectedFirst = expected.find(row => row.date.slice(0, 10) === actualFirst?.date.slice(0, 10) && row.store_id === actualFirst?.store_id && row.dept_id === actualFirst?.dept_id)
  const uniqueDates = useMemo(() => new Set([...actual.map(row => row.date.slice(0, 10)), ...expected.map(row => row.date.slice(0, 10))]), [actual, expected])
  const simple = actual.length === 1 && expected.length === 1
  const clearImported = () => { setExpected([]); setCalendar([]); drafts.clearAnomalyDraft() }
  const loadDemo = () => { drafts.clearAnomalyDraft(); setActual(anomalyDemo.actual_sales); setExpected(anomalyDemo.expected_sales); setCalendar([]); setIncludeIf(false) }
  const submit = (event: React.FormEvent) => { event.preventDefault(); mutation.mutate({ actual_sales: actual, expected_sales: expected, calendar_context: calendar.length ? calendar : null, include_if_diagnostic: includeIf }) }
  return <div className="workflow-page anomaly-page">
    <PageHeader eyebrow="Demand intelligence" title="Sales Anomaly Preview" description="Did observed sales differ unusually from expected sales?" />
    {imported && <Banner tone="info" title="Expected sales imported from Forecasting"><div>Expected sales imported from Forecasting. Enter observed actual sales before running the stateless anomaly preview.</div><button type="button" className="button ghost" onClick={clearImported}>Clear imported expected sales</button></Banner>}
    <Banner tone="warning" title="Preview only">Anomaly does not imply causal diagnosis. The statistical policy is fixed at |score| ≥ 3; top-five review priority is separate.</Banner>
    <form onSubmit={submit}><section className="input-workspace" aria-labelledby="anomaly-input-title">
      <div className="workspace-heading"><div><div className="eyebrow">Observed vs expected</div><h2 id="anomaly-input-title">Review the comparison</h2><p>{demoLabels.anomalies} · Stateless HTTP preview</p></div><button className="button secondary" type="button" onClick={loadDemo}>Load demo input</button></div>
      {simple ? <div className="anomaly-comparison"><div className="comparison-context"><span><CalendarDays size={17} /> Date</span><strong>{actualFirst?.date.slice(0, 10) ?? 'Not supplied'}</strong><small>{actualFirst?.store_id ?? '—'} · {actualFirst?.dept_id ?? '—'}</small></div><div><span>Actual sales</span><strong>{actualFirst?.actual_sales ?? '—'}</strong></div><div><span>Expected sales</span><strong>{expectedFirst?.expected_sales ?? '—'}</strong></div><div className="difference"><span>Difference</span><strong>{actualFirst && expectedFirst ? `${actualFirst.actual_sales - expectedFirst.expected_sales >= 0 ? '+' : ''}${actualFirst.actual_sales - expectedFirst.expected_sales}` : '—'}</strong></div><div><span>Calendar context</span><strong>{calendar.length ? `${calendar.length} row${calendar.length === 1 ? '' : 's'}` : 'Not supplied'}</strong></div></div> : <div className="input-summary"><div><span>Actual rows</span><strong>{actual.length}</strong></div><div><span>Expected rows</span><strong>{expected.length}</strong></div><div><span>Unique dates</span><strong>{uniqueDates.size}</strong></div><div><span>Calendar context</span><strong>{calendar.length ? `${calendar.length} rows` : 'Not supplied'}</strong></div></div>}
      <Disclosure summary="Advanced input"><p className="muted small">Complete payload editors. The one-date backend contract remains authoritative; multiple dates are not altered or truncated.</p><div className="json-grid"><JsonEditor id="actual" label="Observed actual sales — required" value={actual} onChange={setActual} help="A forecast cannot supply observations. Enter actual sales after they occur." /><JsonEditor id="expected" label="Expected sales" value={expected} onChange={setExpected} /></div><div style={{ marginTop: 14 }}><JsonEditor id="calendar-context" label="Optional calendar context" value={calendar} onChange={setCalendar} help="Context can aid review; it is not a causal explanation." /></div><label className="checkbox-row"><input type="checkbox" checked={includeIf} onChange={event => setIncludeIf(event.target.checked)} />Include Isolation Forest secondary diagnostic</label></Disclosure>
      <div className="workspace-action"><RunButton pending={mutation.isPending}>Preview anomalies</RunButton><span>Exactly one date per batch</span></div>
    </section></form>
    {mutation.isError && <ErrorState error={mutation.error} />}
    {mutation.data ? <section className="result-zone" aria-labelledby="anomaly-result-title"><div className="result-heading"><div><div className="eyebrow">Preview result</div><h2 id="anomaly-result-title">Observed sales assessment</h2></div><span className="stateless-label">Non-mutating preview</span></div><Warnings warnings={mutation.data.meta.warnings} />
      {rows[0] && <div className="metric-cluster anomaly-metrics"><div><span>Actual sales</span><strong>{rows[0].actual_sales}</strong></div><div><span>Expected sales</span><strong>{rows[0].expected_sales}</strong></div><div><span>Residual / difference</span><strong>{rows[0].residual >= 0 ? '+' : ''}{rows[0].residual}</strong></div><div><span>Robust anomaly score</span><strong>{rows[0].anomaly_score?.toFixed(3) ?? 'Undefined'}</strong></div></div>}
      <div className="status-split"><article className={rows.some(row => row.is_statistical_alert) ? 'alert' : 'clear'}><span>Statistical status</span>{rows.some(row => row.is_statistical_alert) ? <ArrowUpRight /> : <ArrowDownRight />}<h3>{rows.some(row => row.is_statistical_alert) ? 'Alert' : 'No statistical alert'}</h3><p>|score| ≥ 3 is the frozen statistical-alert threshold.</p></article><article className={priority.length ? 'review' : 'clear'}><span>Review status</span><ScanSearch /><h3>{priority.length ? 'Review priority' : 'Not selected for review'}</h3><p>Top-five review priority is a separate operational ranking.</p></article></div>
      <div className="primary-chart"><ChartContainer title="Robust anomaly scores" summary={`${rows.filter(row => row.is_statistical_alert).length} statistical alerts and ${priority.length} review-priority rows. Dashed lines mark the fixed ±3 threshold.`}><ResponsiveContainer><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis domain={['auto', 'auto']} /><Tooltip /><ReferenceLine y={3} stroke="#b42318" strokeDasharray="5 4" label="+3" /><ReferenceLine y={-3} stroke="#b42318" strokeDasharray="5 4" label="−3" /><ReferenceLine y={0} stroke="#64748b" /><Bar dataKey="anomaly_score" fill="#5b35d5" /></BarChart></ResponsiveContainer></ChartContainer></div>
      <Disclosure summary="Technical details"><Table caption="Stateless anomaly preview results" headers={['Date', 'Store', 'Dept', 'Actual', 'Expected', 'Residual', 'Robust score', 'Direction', 'Statistical alert', 'Review rank', 'Review priority', 'IF score']} rows={rows.map(row => [row.date.slice(0, 10), row.store_id, row.dept_id, row.actual_sales, row.expected_sales, row.residual, row.anomaly_score?.toFixed(3) ?? row.undefined_score_reason ?? '—', row.direction, <StatusBadge status={row.is_statistical_alert ? 'danger' : 'success'}>{row.is_statistical_alert ? 'Alert' : 'Normal'}</StatusBadge>, row.daily_review_rank ?? '—', row.is_review_priority ? 'Priority' : 'No', row.if_anomaly_score?.toFixed(3) ?? 'Not requested'])} /></Disclosure>
    </section> : <section className="pre-result"><EmptyState>Review the aligned comparison, then preview its robust residual score.</EmptyState></section>}
  </div>
}
