from datetime import datetime
from pydantic import Field
from .common import StrictModel,ResponseMeta
class InventoryInputRow(StrictModel): snapshot_date:datetime; store_id:str; dept_id:str; on_hand_inventory:float=Field(ge=0); on_order_inventory:float=Field(ge=0); backorders:float=Field(ge=0); lead_time_days:int=Field(ge=0); review_period_days:int=Field(ge=1); service_level_target:float=Field(ge=.5,le=.999); minimum_order_quantity:float|None=Field(default=None,gt=0); case_pack_size:int|None=Field(default=None,gt=0); maximum_order_quantity:int|None=Field(default=None,gt=0); uncertainty_method:str="robust_normal"; safety_buffer_days:int|None=Field(default=None,ge=0,le=28); recent_anomaly_context:str|None=None
class InventoryForecastRow(StrictModel): forecast_date:datetime; store_id:str; dept_id:str; predicted_sales:float=Field(ge=0)
class InventoryRequest(StrictModel): inventory_inputs:list[InventoryInputRow]; forecasts:list[InventoryForecastRow]
class InventoryRow(StrictModel):
    snapshot_date:datetime; store_id:str; dept_id:str; on_hand_inventory:float; on_order_inventory:float; backorders:float; inventory_position:float; lead_time_days:int; review_period_days:int; protection_period_days:int; forecast_lead_time_demand:float; forecast_protection_demand:float; expected_daily_demand:float; uncertainty_method:str; safety_buffer_days:int|None=None; historical_residual_count:int; historical_residual_mad:float; forecast_uncertainty_scale:float; service_level_target:float; safety_stock:float; target_stock:float; unconstrained_order_quantity:float; minimum_order_quantity:float|None=None; case_pack_size:int|None=None; pre_max_constrained_quantity:int; maximum_order_quantity:int|None=None; recommended_order_quantity:int; replenishment_needed:bool; days_of_cover:float|None=None; constraint_warning:str|None=None; recent_anomaly_context:str|None=None; planning_status:str; planning_warning:str
class InventoryResponse(StrictModel): meta:ResponseMeta; rows:list[InventoryRow]
